FROM python:3.11.16-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /opt/app
COPY pyproject.toml README.md ./
COPY src ./src
RUN python -m pip install --no-cache-dir '.[dev]'
COPY migrations ./migrations
COPY alembic.ini ./
COPY tests ./tests

CMD ["pytest", "tests/integration/test_db.py"]
